project:
  type: website
  output-dir: _site
  preview:
    port: 12800
  resources:
    - assets/images/
    - assets/brand/
    - assets/js/

metadata-files:
  - _announcement.yml
  - _footer.yml
  - _navbar.yml
  - _sidebars.yml

format:
  html:
    quarto-required: 1.9.*
    theme:
      - "assets/style/_base.scss"
      - "assets/style/_tokens.scss"
      - "assets/style/_mixins.scss"
      - "assets/style/components/buttons.scss"
      - "assets/style/components/carousel.scss"
      - "assets/style/components/crumbs.scss"
      - "assets/style/components/cta.scss"
      - "assets/style/components/dotnav.scss"
      - "assets/style/components/featuregrid.scss"
      - "assets/style/components/footer.scss"
      - "assets/style/components/general.scss"
      - "assets/style/components/hero.scss"
      - "assets/style/components/imagestack.scss"
      - "assets/style/components/navbar.scss"
      - "assets/style/components/newsletter.scss"
      - "assets/style/components/richlist.scss"
      - "assets/style/components/status.scss"
    include-after-body:
      - file: _template/dotnav.html
      - file: _template/header.html
      - file: _template/iconify.html
      - file: _template/footer.html
    anchor-sections: false
    smooth-scroll: true
    # tabsets: true
    respect-user-color-scheme: true
    toc: false
    cap-location: bottom
    # page-layout: custom
    grid:
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 0px
    # appendix-style:
    # title-block-style: none
    # title-block-banner: "#ff0000"
    # title-block-categories: true
    execution:
      echo: false
      warning: true
    lightbox: true
    link-external-icon: true
    link-external-newwindow: true
    lang: "en"
    axe: true
    # include-before-body:
    # include-after-body:
    # include-in-header:
    # resources:

website:
  title: "OpenSpace"
  description: "Official OpenSpace Website"
  favicon: "/assets/brand/favicon.webp"
  image: "/assets/brand/logo.webp"
  image-alt: "OpenSpace"
  site-url: "https://testing.www.openspaceproject.com"
  # repo-url: "https://github.com/OpenSpace/www.openspaceproject.com"
  # repo-link-target: "_blank"
  # repo-actions: [edit, issue]
  llms-txt: true
  # google-analytics:
  # cookie-consent:
  #   type: express
  #   style: simple
  #   palette: dark
  #   policy-url: www.openspaceproject.com
  search: false

  # body-header:
  body-footer: ""
  page-navigation: false
  back-to-top-navigation: false
  bread-crumbs: true
  # page-footer:
  open-graph: true
  # twitter-card:
  #   creator: "@openspaceproj"
  #   site: "@openspaceproj"
  # other-links:
  # code-links:
  draft-mode: unlinked

  # margin:


  # listing:

execute:
  echo: false
  output: asis

filters:
  - panel-accordion
  - openspace

extensions:
  iconify:
    set: "octicon"
    # size: "Huge"
    # width: "1em"
    # height: "1em"
    # flip: "horizontal"
    # rotate: "90deg"
    mode: "svg"
    style: "color: #ecf5fb;"
  openspace:

# List of available icons:  https://fontawesome.com/search?ic=free-collection
# List of available icons:  https://icon-sets.iconify.design/   via   https://github.com/mcanouil/quarto-iconify
