project:
  type: website
  output-dir: _site
  preview:
    port: 12800

metadata-files:
  - _announcement.yml
  - _footer.yml
  - _navbar.yml
  - _sidebars.yml

  # resources:
    # - assets/js/slider.js

format:
  html:
    quarto-required: 1.9.*
    theme:
      # light:
      #   - "assets/style/brand.scss"
      #   - "assets/style/openspace-theme.scss"
      #   - "assets/style/openspace-theme-light.scss"
      # dark:
        - "assets/style/brand.scss"
        - "assets/style/openspace-theme-dark.scss"
        - "assets/style/hero.scss"
        - "assets/style/navbar.scss"
        - "assets/style/use-cases.scss"
        - "assets/style/annual-meeting.scss"
    include-after-body:
      - file: _template/hero.html
    anchor-sections: false
    smooth-scroll: true
    # tabsets: true
    respect-user-color-scheme: true
    toc: false
    cap-location: bottom
    # page-layout: custom
    grid:
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 0px
    # appendix-style:
    # title-block-style: none
    # title-block-banner: "#ff0000"
    # title-block-categories: true
    execution:
      echo: false
      warning: true
    lightbox: true
    link-external-icon: true
    link-external-newwindow: true
    lang: "en"
    axe: true
    # include-before-body:
    # include-after-body:
    # include-in-header:
    # resources:

website:
  title: "OpenSpace"
  description: "Official OpenSpace Website"
  favicon: "/assets/logos/openspace/favicon.webp"
  image: "/assets/logos/openspace/logo.webp"
  image-alt: "OpenSpace"
  site-url: "https://www.openspaceproject.com"
  # repo-url: "https://github.com/OpenSpace/www.openspaceproject.com"
  # repo-link-target: "_blank"
  # repo-actions: [edit, issue]
  llms-txt: true
  # google-analytics:
  # cookie-consent:
  #   type: express
  #   style: simple
  #   palette: dark
  #   policy-url: www.openspaceproject.com
  search: false

  # body-header:
  body-footer: ""
  page-navigation: false
  back-to-top-navigation: false
  bread-crumbs: true
  # page-footer:
  open-graph: true
  # twitter-card:
  #   creator: "@openspaceproj"
  #   site: "@openspaceproj"
  # other-links:
  # code-links:
  draft-mode: unlinked

  # margin:


  # listing:

execute:
  echo: false
  output: asis

filters:
  - panel-accordion

extensions:
  iconify:
    set: "octicon"
    # size: "Huge"
    # width: "1em"
    # height: "1em"
    # flip: "horizontal"
    # rotate: "90deg"
    inline: true
    mode: "svg"
    style: "color: #ecf5fb;"

# List of available icons:  https://fontawesome.com/search?ic=free-collection
# List of available icons:  https://icon-sets.iconify.design/   via   https://github.com/mcanouil/quarto-iconify
