# Location
We're excited to welcome you to the **Visualization Center C** in the beautiful city of Norrköping, Sweden. The [Visualization Center C](https://visualiseringscenter.se/en/) is a digital science center with a planetarium that is driven in partnership with the Norrköping municipality and Linköping University as a research environment.

Norrköping is an old industrial town located about 90 minutes south west of Stockholm and is very easy to reach internationally.   Recommended paths are either through Stockholm Arlanda (**ARN**) or Linköping City Airport (**LPI**). Specifically LPI has good connections to Amsterdam Schiphol (**AMS**) which is one of the airline major hubs of Europe.

Summer is an amazing time for a visit in the North. Located about 1600 km / 1000 miles south of the Arctic Circle during the days of the meeting we will have about 14.5h of daylight and only 3.5h of true night (from 23:00 to 02:45).

# Hotels
Hotels in the the city are about $100 per day with suggestions:

  - [Hotel President](https://ligula.se/en/profilhotels/profilhotels-president/)
  - [Elite Grand Hôtel](https://www.elite.se/en/hotels/norrkoping/elite-grand-hotel-norrkoping/)
  - [Hotel Comfort](https://www.strawberry.se/hotell/sverige/norrkoping/comfort-hotel-norrkoping)
